scheduler:
    database: false
    configs:
        -   id: test_one_task_5
            task: testTwoTask
            corn: "0/5 * * * * ?"
            desc: 测试定时任务配置2

        -   id: test_one_task_3
            task: testOneTask
            corn: "0/3 * * * * ?"
            desc: 测试定时任务配置1

        -   id: test_one_task_4
            task: httpTask
            corn: "0/4 * * * * ?"
            desc: 测试http定时任务
            url: http://www.baidu.com